Compatibility
This makes it work.

diff --git a/tests/runc b/tests/runc
--- a/tests/runc
+++ b/tests/runc
@@ -34,6 +34,7 @@ COLOR_IDS=(
 CONTAINER_ID_FILE="/tmp/container-id"
 SYSTEMD_FLAGS="--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
 
+# String and Array Methods
 function .join() {
   local separator="$1" && shift
 
@@ -78,9 +79,9 @@ function .to-upper() {
   echo $@ | awk '{print toupper($0);}'
 }
 
+# Terminal Utilities
 function .is-terminal() {
-  local rc=$(test -t 1)
-  return $rc
+  test -t 1
 }
 
 function .set-fg-color() {
@@ -105,6 +106,7 @@ function .term-reset() {
   tput sgr0
 }
 
+# Logging Utilities
 function .debug () {
   if .is-log-allowed debug ; then
     .log debug $@
@@ -178,6 +180,27 @@ function .log() {
     .term-reset
 }
 
+# Docker Utilities
+function .get-container-image() {
+  local container_id="$1"
+
+  docker ps -a --filter Id=${container_id} --format '{{.Image}}'
+}
+
+function .get-container-id() {
+  test -f "${CONTAINER_ID_FILE}" && cat "${CONTAINER_ID_FILE}"
+}
+
+# YAML Utilities
+function .yaml2json() {
+  local yml_file="$1"
+
+  # load a file as yaml, dump as json
+  python -c 'import json as j, sys as s, yaml as y; print(j.dumps(y.load(open(s.argv[1], "r").read()), indent=2))' \
+    $yml_file
+}
+
+# General Usage
 function .usage() {
   (
     echo "usage: ${0:-runc} [start|exec]"
@@ -189,6 +212,7 @@ function .usage() {
   return 1
 }
 
+# Start Command
 function .usage-start() {
   (
     echo "usage ${0:-runc} start image [is_systemd]"
@@ -242,33 +266,48 @@ function .start() {
   .info "Container ${container_id} started."
 }
 
+# Exec Command
 function .usage-exec() {
   (
-    echo "usage: ${0:-} exec args..."
+    echo "usage: ${0:-} exec [-i] command args..."
     echo
-    echo "  arguments to exec command:"
-    echo "    args...  Arbitrary arguments to execute in the container."
+    echo "  arguments:"
     echo
-    echo "             Environment variables matching container_env_* will be"
-    echo "             renamed and capitalized such that container_env_term"
-    echo "             will be set in the container as TERM."
+    echo "    [-i|--interactive]  Optionally run in interactive mode."
+    echo "    command             The executable to use as an entry point."
+    echo "    args...             Arguments to provide to the command in the container."
+    echo
+    echo "Environment Variables"
+    echo "---------------------"
+    echo "Environment variables matching container_env_* will be renamed and capitalized"
+    echo "such that container_env_term will be set in the container as TERM."
     echo
   ) >&2
   return 1
 }
 
 function .exec() {
-  if [ $# -lt 1 ]; then
+  if [ "$1" == "-i" -o "$1" == "--interactive" ]; then
+    local interactive=y
+    shift
+  fi
+
+  if [ $# -lt 1 ] || [ "$1" == "-h" -o "$1" == "--help" ]; then
+    # if help is needed, provide it
     .usage-exec
   fi
 
-  local container_id="$(test -f "${CONTAINER_ID_FILE}" && cat "${CONTAINER_ID_FILE}")"
+  local command="$1"
+  shift
+
+  local args=("$@")
+  local container_id="$(.get-container-id)"
+
   if [ -z "${container_id}" ]; then
     .error "There is no container running."
     return 1
   fi
 
-  local command=("$@")
   local env_variables=""
 
   for container_env_var_name in $(env | grep -oP '^container_env_[-_\w\d]+') ; do
@@ -279,24 +318,103 @@ function .exec() {
 
   test -z "${env_variables}" || env_variables="env ${env_variables}"
 
+  .debug "environment: $(echo "${env_variables}" | cut -b 4-)"
+  .debug "command: ${command}"
+
   local argindex=$((0))
-  for arg in "${command[@]}" ; do
-    if [ $argindex -eq 0 ]; then
-      .debug "command: ${arg}"
-    else
-      .debug "arg[$(printf '%d' $argindex)]: ${arg}"
-    fi
+  for arg in "${args[@]}" ; do
+    .debug "arg[$(printf '%d' $argindex)]: ${arg}"
     argindex=$(($argindex + 1))
   done
 
   .info "Executing command \"${env_variables} ${command[*]}\" in container ${container_id}"
-  docker exec --tty ${container_id} ${env_variables} ${command[*]}
+  docker exec $(test ! -z "${interactive}" && echo '-i') --tty ${container_id} ${env_variables} ${command} ${args[@]}
 }
 
+# Stop Command
+function .usage-stop() {
+  (
+    echo "usage: ${0:-} stop"
+    echo "Stops the current VM if running."
+    echo
+  ) >&2
+  return 1
+}
+
+function .stop() {
+  local container_id="$(test -f ${CONTAINER_ID_FILE} && cat ${CONTAINER_ID_FILE})"
+
+  if [ -z "$container_id" ]; then
+    .error "No VM running."
+    return 1
+  fi
+
+  .info "Stopping Container ${container_id}..."
+
+  if docker ps --filter Id=${container_id} --format '{{.ID}}' | grep -q '.*' ; then
+    .debug "Container running, issuing a Docker kill command"
+    docker kill ${container_id} >/dev/null
+  else
+    .debug "Container not running, nothing to do."
+  fi
+
+  .info "Cleaning Up..."
+
+  if docker ps -a --filter Id=${container_id} --format '{{.ID}}' | grep -q '.*' ; then
+    .debug "Traces of the container remain, removing them with Docker rm"
+    docker rm --force --volumes ${container_id} >/dev/null
+  else
+    .debug "No traces of the container remain."
+  fi
+
+  # important! remove the container id file
+  rm -f ${CONTAINER_ID_FILE}
+}
+
+# Status Command
+function .usage-status() {
+  (
+    echo "usage: ${0:-} status"
+    echo "Report the status of the VM."
+    echo
+  ) >&2
+  return 1
+}
+
+function .status() {
+  local container_id="$(test -f ${CONTAINER_ID_FILE} && cat ${CONTAINER_ID_FILE})"
+
+  if [ -z "$container_id" ] && ! docker ps --filter Id=${container_id} --format '{{.ID}}' | grep -q '.*' ; then
+    .set-fg-color yellow && .term-bold && \
+      echo "No VM running." && \
+      .term-reset
+
+    # attempt to clean up
+    docker ps -a --filter Id=${container_id} --format '{{.ID}}' | grep -qP '.+' &&
+      docker rm --force --volumes ${container_id} >/dev/null || true
+
+    rm -f ${CONTAINER_ID_FILE}
+    return 1
+  fi
+
+  local image="$(.get-container-image ${container_id})"
+
+  .set-fg-color green && .term-bold && \
+    echo "${image}: running " && \
+    .term-reset && \
+    echo "  (${container_id})"
+
+  return 0
+}
+
+# Main Entrypoint
 function .main() {
   if [ $# -eq 0 ]; then
     .usage
   fi
+
+  # set this if it's undefined
+  export role_name="${role_name:-$(.yaml2json "$FILE_DIR/../meta/main.yml" | jq -r '.galaxy_info.name')}"
 
   while [ $# -gt 0 ]; do
     case $1 in
@@ -308,6 +426,16 @@ function .main() {
       exec)
         shift
         .exec "$@"
+        break
+        ;;
+      stop)
+        shift
+        .stop "$@"
+        break
+        ;;
+      status)
+        shift
+        .status "$@"
         break
         ;;
       *)
